todo/todo/urls.py
from django.contrib import admin
from django.urls import path, include
from todoapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('todoapp/', include('todoapp.urls')),  # Remove the leading slash
    path('logout/', views.u_logout, name='logout')
]

todo/todoapp/urls.py
from django.urls import path
from .  import views


app_name = 'todo_app'

urlpatterns = [

    path('register/', views.register,name='register'),
    path('login/',views.u_login,name='login'),
    path('task/',views.to_do,name='task'),
    path('view_task',views.records,name='view_task'),

]

todo/todoapp/models.py
from django.db import models
from django.conf import settings

# Create your models here.

class User_info(models.Model):

   user  = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
   instagram = models.URLField(blank = True)
 


   def __str__(self):
      return self.user.username
   

class Tlist(models.Model):
   item = models.CharField(unique=True,max_length=250)

   def __str__(self):
         return self.item
   description = models.CharField(max_length=1000)

   def __str__(self):
      return self.description
   completion_date = models.DateField()
   
   def __str__(self):
      return str(self.completion_date) 
   

todo/todoapp/forms.py
from  .models import User_info,Tlist
from django.contrib.auth.models import User
from django import forms


class New_User(forms.ModelForm):

    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'password', 'email')



class UserProfileInfoform(forms.ModelForm):
    class Meta():
        model = User_info
        fields = ('instagram',)



class Task(forms.ModelForm):
    class Meta():
        model = Tlist
        fields = ('item','description','completion_date')
        

todo/todoapp/views.py
from django.shortcuts import render
from django.contrib.auth import login,logout,authenticate
from django.urls import reverse
from .models import Tlist
from .forms import New_User,UserProfileInfoform,Task
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse,HttpResponseRedirect


# Create your views here.


def index(request):
    return render(request, 'todo/index.html')




@login_required
def records(request):
    title_dict = Tlist.objects.order_by('completion_date')
    real_dict = {'tasks':title_dict}

    return render(request,'todo/tasks.html',real_dict)



@login_required
def special(request):
    # Remember to also set login url in settings.py!
    # LOGIN_URL = '/basic_app/user_login/'
    return HttpResponse("You are logged in. Nice!")


@login_required
def u_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

@login_required
def to_do(request):
    form = Task()

    if request.method == 'POST':
        form = Task(request.POST)

        if form.is_valid():
            form.save(commit=True)
            return HttpResponse("YOUR NEW TASK WAS SAVED SUCCESFULLY...")

        else:
            print("Invalid form was given")
            return HttpResponse("you did not fill in the form in a valid way")
        
    
    return render(request,'todo/todo_list.html',{'todo_list':form})
        


def register(request):

    registered = False

    if request.method == 'POST':

        user_form = New_User(data=request.POST)
        profile_form = UserProfileInfoform(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
           user = user_form.save()


           user.set_password(user.password)
           user.save()

          

           profile = profile_form.save(commit=False)
           

           profile.user = user

           registered = True

        else:
            # One of the forms was invalid if this else gets called.
            print(user_form.errors,profile_form.errors)

    else:
        user_form = New_User()
        profile_form = UserProfileInfoform()

    
    return render(request, 'todo/register.html',
                  {'registered':registered,
                   'user_form':user_form,
                   'profile_form': profile_form,})


def u_login(request):

    if request.method == 'POST':

        username = request.POST.get('username')
        password = request.POST.get('password')


        user = authenticate(username=username,password=password)

        if user:

            if user.is_active:

                login(request,user)

                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("This account is no longer active sorry for any inconviniences caused..")
            
        else:
            print("SUSPICIOUS USER TRIED TO LOG IN")
            return HttpResponse("We do not recognise you")
            
    else:
      return render(request,'todo/login.html',{})
        

            

todo/templates/todo/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TODO APP</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'admin:index' %}">DJANGO</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'index' %}">Home</a>
              </li>
              
             

              {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'logout' %}">LOGOUT</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'todo_app:task' %}">NEW TASK</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'todo_app:view_task' %}">VIEW ALL TASKS</a>
              </li>
              {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'todo_app:register' %}">Register</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'todo_app:login' %}">LOGIN</a>
              </li>
              
              {% endif %}
             
            </ul>
          </div>
        </div>
      </nav>
      {% block body_block %}

      {% endblock %}
    
</body>
</html>

todo/templates/todo/index.html
<!DOCTYPE html>
{% extends "todo/base.html" %}
{% block body_block %}
<div class="container">
<h1>Welcome to the to-do list app</h1>
<p>Feel at Home..</p>
</div>

{% endblock %}

todo/templates/todo/login.html
<!DOCTYPE html>
{% extends 'todo/base.html'%}
{% block body_block %}

<div class="container">
    <form action="" method="post">
        
    <h4>HI THERE!</h4>
        {% csrf_token %}
    <input type="text" name="username" id="" placeholder="USERNAME">
    <input type="password" name="password" id="" placeholder="PASSWORD"">
    <input type="submit" class="btn btn-warning" name="" id="" value="LOGIN">
    </form>
</div>



{% endblock %}

todo/templates/todo/register.html
<!DOCTYPE html>
{% extends 'todo/base.html' %}
{% block body_block %}

<div class="container">
    {% if registered %}

    <h1>Thank you for registering...</h1>

    {% else %}
    <h1>Fill in the form below to register </h1>
    <form enctype="multipart/form-data" method="post">
        {% csrf_token  %}
        {{ user_form.as_p }}
        {{ profile_form.as_p }}
        <input type="submit" value="submit" class="btn btn-primary">
    </form>
    {% endif %}
  
    
</div>

{% endblock %}

todo/templates/todo/tasks.html
<!DOCTYPE html>
{% extends 'todo/base.html' %}
{% block body_block %}
<div class="container">
   {% if tasks %}
     <table>
        <thead>
            <th>TITLE</th>
            <th>DESCRIPTION</th>
            <th>COMPLETION DATE</th>
        </thead>

        {% for a in tasks %}
        <tr>
            <td>{{ a.item }}</td>
            <td>{{ a.description }}</td>
            <td>{{ a.completion_date }}</td>
        </tr>
        {% endfor %}
     </table>
    {% endif %}
</div>
{% endblock %}

todo/templates/todo/todo_list.html
<!DOCTYPE html>
{% extends 'todo/base.html' %}
{% block body_block %}

<div class="container">
    <h3>ADD SOMETHING YOU WANT TO DO BELOW.....</h3>
    <form action="" method="post">
    {% csrf_token %}
    {{ todo_list.as_p }}
    <input type="submit" value="ADD TASK" class="btn btn-danger">
    </form>

</div>

{% endblock %}